version: "3"

name: "slot"

services:
  redis:
    image: redis:alpine
    expose:
      - 6379
    networks:
      - netbase
    ports:
      - 33061:6379
    restart: always

  web:
    build: ./
    ports:
      - 4000:4000
    environment:
      - LISTEN_PORT=4000
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
    #restart: always
    networks:
      - netbase

networks:
  netbase:
    external: true
